kind: PersistentVolume
apiVersion: v1
metadata: 
  name: local-persistant-volume
  namespace: ns-nginx
  labels:
    app: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data

