kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
  name: local-persistent-volume-claim
  namespace: ns-ingress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage

