kind: Job
apiVersion: batch/v1
metadata:
  name: demo-job
  namespace: ns-nginx
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: demo-job-pod
      labels:
        app: batch-job
    spec:
      containers:
        - name: container-batch-job
          image: busybox:latest
          command: ["sh", "-c", "echo HELLO DOSTO! && sleep 10"]
      restartPolicy: Never

