kind: ReplicaSet
apiVersion: apps/v1
metadata: 
  name: replicaset-nginx
  namespace: ns-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-nginx
  template:
    metadata:
      name: replicaset-pod-nginx
      labels:
        app: app-nginx
    spec:
      containers:
        - name: container-nginx
          image: nginx:latest
          ports:
            - containerPort: 80
